version: '2'
volumes:
  settings:
services:
  kiosk:
    restart: always
    build: ./kiosk
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - 'settings:/usr/src/app/settings'
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  # wifi-connect:
  #   build: ./wifi-connect
  #   restart: always
  #   network_mode: host
  #   privileged: true
  #   labels:
  #     io.balena.features.dbus: '1'
  #     io.balena.features.firmware: '1'
  photos:
    privileged: true
    restart: always
    build: ./photos
    ports:
      - "8888:8888"


  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
        - './etc-pihole/:/etc/pihole/'
        - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped